[profile.release]
debug = true

[workspace]
members = [
  "components/airlock",
  "components/builder-api",
  "components/builder-core",
  "components/builder-db",
  "components/builder-graph",
  "components/builder-jobsrv",
  "components/builder-protocol",
  "components/builder-router",
  "components/builder-worker",
  "components/github-api-client",
  "components/net",
  "components/oauth-client",
  "components/segment-api-client"
]
