log_dir = "{{pkg.svc_var_path}}"

[ui]
root = "{{pkg.svc_static_path}}"

[http]
{{toToml cfg.http}}

[oauth]
{{toToml cfg.oauth}}

[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}

[segment]
{{toToml cfg.segment}}

{{~#eachAlive bind.router.members as |member|}}
[[routers]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/eachAlive}}

{{#eachAlive bind.jobsrv.members as |member| ~}}
    {{#if @first ~}}
    "[jobsrv]"
      "host" : "{{member.sys.ip}}",
      "port" : "{{member.cfg.port}}"
    {{/if ~}}
  {{/each ~}}

[depot]
path = "{{pkg.svc_data_path}}"
log_dir = "{{pkg.svc_var_path}}"
key_dir = "{{pkg.svc_files_path}}"
{{toToml cfg.depot}}

[s3]
{{toToml cfg.s3}}
