[package]
name = "github-api-client"
version = "0.0.0"
authors = ["Jamie Winsor <reset@habitat.sh>", "Josh Black <raskchanky@gmail.com>"]
workspace = "../../"

[dependencies]
base64 = "*"
frank_jwt = "*"
reqwest = "*"
log = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"

# For metrics library
[dependencies.builder_core]
path = "../builder-core"
