log_level = "info"
jobsrv_enabled = true

[http]
listen = "0.0.0.0"
port   = 9636

[oauth]
provider       = "github"
token_url      = "https://github.com/login/oauth/access_token"
userinfo_url   = "https://api.github.com/user"
redirect_url   = ""
client_id      = ""
client_secret  = ""

[github]
api_url        = "https://api.github.com"
app_id         = 5565
webhook_secret = ""

[depot]
builds_enabled          = true
non_core_builds_enabled = true
events_enabled          = false
jobsrv_enabled          = true

[segment]
url       = "https://api.segment.io"
write_key = ""

[s3]
backend = "minio"
key_id = "depot"
secret_key = "password"
endpoint = "http://localhost:9000"
bucket_name = "habitat-builder-artifact-store.default"
