[package]
name = "habitat-builder-protocol"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
description = "Habitat Builder Network Server Protocol"
build = "build.rs"
workspace = "../../"

[dependencies]
clippy = { version = "*", optional = true }
fnv = "*"
protobuf = "2.0.*"
serde = "*"
serde_derive = "*"
time = "*"
regex = "*"
lazy_static = "*"
grpcio = "0.3.0"
futures = "0.1.*"

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

[build-dependencies]
pkg-config = "0.3"
protoc = "2.0.*"
protoc-rust = "2.0"
protoc-grpcio = "0.2.0"
protobuf-codegen = "2.0"
