[package]
name = "oauth-client"
version = "0.0.0"
authors = ["Josh Black <raskchanky@gmail.com>"]
description = "OAuth Client"
workspace = "../../"

[dependencies]
log = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

# For metrics library
[dependencies.builder_core]
path = "../builder-core"
